name: Deploy to GKE with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Create credentials file
        run: |
          echo '${{ secrets.SA_KEY }}' 

      - name: Terraform Init
        run: |
          terraform init
        working-directory: ./terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Terraform Plan
        run: |
          run: terraform plan -var="project_id=${{ secrets.PROJECT_ID }}"
        working-directory: ./terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: ./terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials tech-challenge-fiap-pagamento --zone us-central1 --project ${{ secrets.PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ../k8s/
        working-directory: ./terraform
