name: Deploy to GKE with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Terraform Plan
        run: terraform plan -var="credentials=${{ secrets.SA_KEY }}"
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

      - name: Get GKE credentials
        run: |
          echo "${{ secrets.SA_KEY }}" > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud container clusters get-credentials tech-challenge-fiap-pagamento --zone us-central1 --project ${{ secrets.PROJECT_ID }}
        working-directory: ./terraform
        shell: bash

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ../k8s/
        working-directory: ./terraform
